package com.tlabs.posweb.beans;

import java.util.Date;
import java.util.List;




/*
 * Created By	: Satya Narayan Shukla
 * Created On	: 27/11/2018
 * Description	: Model class for customer_ledger table. 
*/



public class CustomerLedger {

	
	private String txnRef;
	
	
	private String walletId;
	
	
	private String phoneNumber;
	
	
	private Date createdDate;
	
	
	private Date updatedDate;
	
	
	private float amountBalance;
	
	
	private float amountDebited;
	
	
	private float amountCredited;
	
	
	private String txnType;
	
	
	private String txnSource;
	
	
	private String userName;
	
	
	private String roleName;
	
	
	private String remarks;
	

	private String customerId;

	
	private String createdDateStr;
	
	
	private String updatedDateStr;
	
	
	private List<CustomerLedger> CustomerLedgers;
	
	
	private CustomerLedger CustomerLedger;
	private Integer quantity;
	private Float maxTopupAmt;
	private boolean autoGenerated;
	private List<CustomerWalletMaster> customerWallets;
	private List<CustomerWalletLocations> customerWalletLocations;
	private String walletSearchCriteria;
	
	private String walletName;
	private String tenderKey;
	
    private boolean importFlag;
    private String fileName;
    private String uploadedfilePath;
    private String filePath;
    private boolean isSaveFile;
    
    
	public String getFilePath() {
		return filePath;
	}
	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}
	public boolean isSaveFile() {
		return isSaveFile;
	}
	public void setSaveFile(boolean isSaveFile) {
		this.isSaveFile = isSaveFile;
	}
	public String getUploadedfilePath() {
		return uploadedfilePath;
	}
	public void setUploadedfilePath(String uploadedfilePath) {
		this.uploadedfilePath = uploadedfilePath;
	}
	public String getFileName() {
		return fileName;
	}
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	public boolean isImportFlag() {
		return importFlag;
	}
	public void setImportFlag(boolean importFlag) {
		this.importFlag = importFlag;
	}
	public Float getMaxTopupAmt() {
		return maxTopupAmt;
	}
	public void setMaxTopupAmt(Float maxTopupAmt) {
		this.maxTopupAmt = maxTopupAmt;
	}
	public String getTenderKey() {
		return tenderKey;
	}
	public void setTenderKey(String tenderKey) {
		this.tenderKey = tenderKey;
	}
	public String getWalletName() {
		return walletName;
	}
	public void setWalletName(String walletName) {
		this.walletName = walletName;
	}
	public boolean isAutoGenerated() {
		return autoGenerated;
	}
	public void setAutoGenerated(boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}
	public Integer getQuantity() {
		return quantity;
	}
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	public String getWalletSearchCriteria() {
		return walletSearchCriteria;
	}
	public void setWalletSearchCriteria(String walletSearchCriteria) {
		this.walletSearchCriteria = walletSearchCriteria;
	}
	public List<CustomerWalletLocations> getCustomerWalletLocations() {
		return customerWalletLocations;
	}
	public void setCustomerWalletLocations(List<CustomerWalletLocations> customerWalletLocations) {
		this.customerWalletLocations = customerWalletLocations;
	}

	private CustomerWalletMaster walletProgram;
	
	
	private String startdate;
	
	
	private String enddate;
	
	
	private String expiryDate;
	
	
	private RequestHeader requestHeader;
	
	
	private ResponseHeader responseHeader;
	
	
	private int totalRecords;
	private int totalWallets;
	
	private String searchCriteria;
	
	
	private String startIndex;
	
	
	private String maxRecords;
	
	private boolean isSaveReport;
	
	
	private float closingBalance;
	
	
	private boolean otpRequired;
	
	
	private String walletProgramName;
	
	
	private Float minBillAmount;
	
	
	private Float maxBillAmount;
	
	
	private Float minCashDeposit;
	
	
	private Float maxCashDeposit;
	
	
	private Float signupCash;
	
	
	private Float activationFee;
	
	
	private boolean status;
	
	
	private String walletProgramId;
	
	
	private List<CustomerLedger> wallets;
	
	
	private boolean transactionRequired;
	
	
	private Float renewalFee;
	
	
	private int renewalPeriod;
	
	
	private boolean autoAssigned;
	
	
	private String walletType;
	
	
	private String customerName;
	
	
	private String walletStatus;
	
	
	private String walletProgramStatus;
	
	private int validityPeriod;
	
	private String country;
	
	
	
	
	
	private String location;
	
	private String zone;
	private List<String> zoneList;
	private List<String> locationsList;


	private String walletMaxRecords;
	

	private String walletStartIndex;
	
	
	
	
	public int getTotalWallets() {
		return totalWallets;
	}
	public void setTotalWallets(int totalWallets) {
		this.totalWallets = totalWallets;
	}
	public String getWalletMaxRecords() {
		return walletMaxRecords;
	}
	public void setWalletMaxRecords(String walletMaxRecords) {
		this.walletMaxRecords = walletMaxRecords;
	}
	public String getWalletStartIndex() {
		return walletStartIndex;
	}
	public void setWalletStartIndex(String walletStartIndex) {
		this.walletStartIndex = walletStartIndex;
	}
	public String getLocation() {
		return location;
	}
	public void setLocation(String location) {
		this.location = location;
	}
	public String getZone() {
		return zone;
	}
	public void setZone(String zone) {
		this.zone = zone;
	}
	public List<String> getZoneList() {
		return zoneList;
	}
	public void setZoneList(List<String> zoneList) {
		this.zoneList = zoneList;
	}
	public List<String> getLocationsList() {
		return locationsList;
	}
	public void setLocationsList(List<String> locationsList) {
		this.locationsList = locationsList;
	}
	public int getValidityPeriod() {
		return validityPeriod;
	}
	public void setValidityPeriod(int validityPeriod) {
		this.validityPeriod = validityPeriod;
	}
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public CustomerWalletMaster getWalletProgram() {
		return walletProgram;
	}
	public void setWalletProgram(CustomerWalletMaster walletProgram) {
		this.walletProgram = walletProgram;
	}
	public String getWalletProgramStatus() {
		return walletProgramStatus;
	}
	public void setWalletProgramStatus(String walletProgramStatus) {
		this.walletProgramStatus = walletProgramStatus;
	}
	public String getWalletStatus() {
		return walletStatus;
	}
	public void setWalletStatus(String walletStatus) {
		this.walletStatus = walletStatus;
	}
	public String getCustomerName() {
		return customerName;
	}
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	public Float getRenewalFee() {
		return renewalFee;
	}
	public void setRenewalFee(Float renewalFee) {
		this.renewalFee = renewalFee;
	}
	public int getRenewalPeriod() {
		return renewalPeriod;
	}
	public void setRenewalPeriod(int renewalPeriod) {
		this.renewalPeriod = renewalPeriod;
	}
	public boolean isAutoAssigned() {
		return autoAssigned;
	}
	public void setAutoAssigned(boolean autoAssigned) {
		this.autoAssigned = autoAssigned;
	}
	public String getWalletType() {
		return walletType;
	}
	public void setWalletType(String walletType) {
		this.walletType = walletType;
	}
	public boolean isTransactionRequired() {
		return transactionRequired;
	}
	public void setTransactionRequired(boolean transactionRequired) {
		this.transactionRequired = transactionRequired;
	}
	public String getWalletProgramId() {
		return walletProgramId;
	}
	public void setWalletProgramId(String walletProgramId) {
		this.walletProgramId = walletProgramId;
	}
	public List<CustomerLedger> getWallets() {
		return wallets;
	}
	public void setWallets(List<CustomerLedger> wallets) {
		this.wallets = wallets;
	}
	public Float getMinBillAmount() {
		return minBillAmount;
	}
	public void setMinBillAmount(Float minBillAmount) {
		this.minBillAmount = minBillAmount;
	}
	public Float getMaxBillAmount() {
		return maxBillAmount;
	}
	public void setMaxBillAmount(Float maxBillAmount) {
		this.maxBillAmount = maxBillAmount;
	}
	public Float getMinCashDeposit() {
		return minCashDeposit;
	}
	public void setMinCashDeposit(Float minCashDeposit) {
		this.minCashDeposit = minCashDeposit;
	}
	public Float getMaxCashDeposit() {
		return maxCashDeposit;
	}
	public void setMaxCashDeposit(Float maxCashDeposit) {
		this.maxCashDeposit = maxCashDeposit;
	}
	public Float getSignupCash() {
		return signupCash;
	}
	public void setSignupCash(Float signupCash) {
		this.signupCash = signupCash;
	}
	public Float getActivationFee() {
		return activationFee;
	}
	public void setActivationFee(Float activationFee) {
		this.activationFee = activationFee;
	}
	public boolean isStatus() {
		return status;
	}
	public void setStatus(boolean status) {
		this.status = status;
	}
	public String getExpiryDate() {
		return expiryDate;
	}
	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}
	public String getWalletProgramName() {
		return walletProgramName;
	}
	public void setWalletProgramName(String walletProgramName) {
		this.walletProgramName = walletProgramName;
	}
	
	private String customerWalletReportFilePath;
	
	public String getCreatedDateStr() {
		return createdDateStr;
	}
	public void setCreatedDateStr(String createdDateStr) {
		this.createdDateStr = createdDateStr;
	}
	public String getUpdatedDateStr() {
		return updatedDateStr;
	}
	public void setUpdatedDateStr(String updatedDateStr) {
		this.updatedDateStr = updatedDateStr;
	}
	public List<CustomerWalletMaster> getCustomerWallets() {
		return customerWallets;
	}
	public void setCustomerWallets(List<CustomerWalletMaster> customerWallets) {
		this.customerWallets = customerWallets;
	}
	public String getWalletId() {
		return walletId;
	}
	public void setWalletId(String walletId) {
		this.walletId = walletId;
	}
	public boolean isOtpRequired() {
		return otpRequired;
	}
	public void setOtpRequired(boolean otpRequired) {
		this.otpRequired = otpRequired;
	}
	public boolean isSaveReport() {
		return isSaveReport;
	}
	public void setSaveReport(boolean isSaveReport) {
		this.isSaveReport = isSaveReport;
	}
	public float getClosingBalance() {
		return closingBalance;
	}
	public void setClosingBalance(float closingBalance) {
		this.closingBalance = closingBalance;
	}
	public String getCustomerWalletReportFilePath() {
		return customerWalletReportFilePath;
	}
	public void setCustomerWalletReportFilePath(String customerWalletReportFilePath) {
		this.customerWalletReportFilePath = customerWalletReportFilePath;
	}
	public String getTxnRef() {
		return txnRef;
	}
	public void setTxnRef(String txnRef) {
		this.txnRef = txnRef;
	}
	public String getCustomerId() {
		return customerId;
	}
	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}
	public String getPhoneNumber() {
		return phoneNumber;
	}
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	public float getAmountBalance() {
		return amountBalance;
	}
	public void setAmountBalance(float amountBalance) {
		this.amountBalance = amountBalance;
	}
	public float getAmountDebited() {
		return amountDebited;
	}
	public void setAmountDebited(float amountDebited) {
		this.amountDebited = amountDebited;
	}
	public float getAmountCredited() {
		return amountCredited;
	}
	public void setAmountCredited(float amountCredited) {
		this.amountCredited = amountCredited;
	}
	public String getTxnType() {
		return txnType;
	}
	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}
	public String getTxnSource() {
		return txnSource;
	}
	public void setTxnSource(String txnSource) {
		this.txnSource = txnSource;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getRoleName() {
		return roleName;
	}
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
	
	public String getRemarks() {
		return remarks;
	}
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	public RequestHeader getRequestHeader() {
		return requestHeader;
	}
	public void setRequestHeader(RequestHeader requestHeader) {
		this.requestHeader = requestHeader;
	}
	public ResponseHeader getResponseHeader() {
		return responseHeader;
	}
	public void setResponseHeader(ResponseHeader responseHeader) {
		this.responseHeader = responseHeader;
	}
	
	public String getSearchCriteria() {
		return searchCriteria;
	}
	public void setSearchCriteria(String searchCriteria) {
		this.searchCriteria = searchCriteria;
	}
	public String getStartIndex() {
		return startIndex;
	}
	public void setStartIndex(String startIndex) {
		this.startIndex = startIndex;
	}
	public String getMaxRecords() {
		return maxRecords;
	}
	public void setMaxRecords(String maxRecords) {
		this.maxRecords = maxRecords;
	}
	
	public String getStartdate() {
		return startdate;
	}
	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}
	public String getEnddate() {
		return enddate;
	}
	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}
	
	public List<CustomerLedger> getCustomerLedgers() {
		return CustomerLedgers;
	}
	public void setCustomerLedgers(List<CustomerLedger> customerLedgers) {
		CustomerLedgers = customerLedgers;
	}
	public CustomerLedger getCustomerLedger() {
		return CustomerLedger;
	}
	public void setCustomerLedger(CustomerLedger customerLedger) {
		CustomerLedger = customerLedger;
	}
	
	public int getTotalRecords() {
		return totalRecords;
	}
	public void setTotalRecords(int totalRecords) {
		this.totalRecords = totalRecords;
	}
}
